;;; lolcat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lolcat.el

(autoload 'lolcat-this-buffer "lolcat" "\
Colorize BUFFER (defaults to the current buffer).

(fn &optional BUFFER)" t)
(autoload 'lolcat-view-file "lolcat" "\
View FILENAME with color.

(fn FILENAME)" t)
(autoload 'lolcat-view-buffer "lolcat" "\
View BUFFER with color.

(fn BUFFER)" t)
(autoload 'lolcat-message "lolcat" "\
Like `message' but with color.

FORMAT-STRING and ARGS are used in the same way as `message'.

(fn FORMAT-STRING &rest ARGS)" t)
(autoload 'eshell/lolcat "lolcat" "\
Display contents of FILENAME with color.

(fn FILENAME)")
(register-definition-prefixes "lolcat" '("lolcat"))

;;; End of scraped data

(provide 'lolcat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lolcat-autoloads.el ends here
