;;; engrave-faces-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from engrave-faces.el

(autoload 'engrave-faces-define-backend "engrave-faces" "\
Create a new engraving backend BACKEND.
EXTENSION is the extension which will be used when writing engraved files.
FACE-TRANSFORMER is the all important function which can be called with a
list of faces and some content to apply those faces to and generate an output
string accordingly.
Should a pre/postable make sense for complete files using BACKEND, a
STANDALONE-TRANSFORMER may be defined which operates on a buffer which has been
generated by `engrave-faces-buffer' and is called after hooks.
If STANDALONE-TRANSFORMER is given it will be used when directly creating a file,
and cause a -standalone version of the buffer transforming function to be created.

(fn BACKEND EXTENSION FACE-TRANSFORMER &optional STANDALONE-TRANSFORMER VIEW-SETUP)" nil t)
(register-definition-prefixes "engrave-faces" '("engrave-faces-"))


;;; Generated autoloads from engrave-faces-ansi.el

 (autoload #'engrave-faces-ansi-buffer "engrave-faces-ansi" nil t)
 (autoload #'engrave-faces-ansi-file "engrave-faces-ansi" nil t)
(register-definition-prefixes "engrave-faces-ansi" '("engrave-faces-ansi-"))


;;; Generated autoloads from engrave-faces-html.el

 (autoload #'engrave-faces-html-buffer "engrave-faces-html" nil t)
 (autoload #'engrave-faces-html-buffer-standalone "engrave-faces-html" nil t)
 (autoload #'engrave-faces-html-file "engrave-faces-html" nil t)
(register-definition-prefixes "engrave-faces-html" '("engrave-faces-html-"))


;;; Generated autoloads from engrave-faces-latex.el

 (autoload #'engrave-faces-latex-buffer "engrave-faces-latex" nil t)
 (autoload #'engrave-faces-latex-buffer-standalone "engrave-faces-latex" nil t)
 (autoload #'engrave-faces-latex-file "engrave-faces-latex" nil t)
(register-definition-prefixes "engrave-faces-latex" '("engrave-faces-latex-"))

;;; End of scraped data

(provide 'engrave-faces-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; engrave-faces-autoloads.el ends here
